//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityAvailabilityStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntityAvailabilityStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Available"/>
 *     &lt;enumeration value="Limited"/>
 *     &lt;enumeration value="Restoring"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntityAvailabilityStatus")
@XmlEnum
public enum EntityAvailabilityStatus {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Available")
    AVAILABLE("Available"),
    @XmlEnumValue("Limited")
    LIMITED("Limited"),
    @XmlEnumValue("Restoring")
    RESTORING("Restoring");
    private final String value;

    EntityAvailabilityStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntityAvailabilityStatus fromValue(String v) {
        for (EntityAvailabilityStatus c: EntityAvailabilityStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
