//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageCountDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageCountDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActiveMessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DeadLetterMessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ScheduledMessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="TransferMessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="TransferDeadLetterMessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageCountDetails", namespace = "http://schemas.microsoft.com/netservices/2011/06/servicebus", propOrder = {
    "activeMessageCount",
    "deadLetterMessageCount",
    "scheduledMessageCount",
    "transferMessageCount",
    "transferDeadLetterMessageCount"
})
public class MessageCountDetails {

    @XmlElement(name = "ActiveMessageCount")
    protected Long activeMessageCount;
    @XmlElement(name = "DeadLetterMessageCount")
    protected Long deadLetterMessageCount;
    @XmlElement(name = "ScheduledMessageCount")
    protected Long scheduledMessageCount;
    @XmlElement(name = "TransferMessageCount")
    protected Long transferMessageCount;
    @XmlElement(name = "TransferDeadLetterMessageCount")
    protected Long transferDeadLetterMessageCount;

    /**
     * Gets the value of the activeMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getActiveMessageCount() {
        return activeMessageCount;
    }

    /**
     * Sets the value of the activeMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActiveMessageCount(Long value) {
        this.activeMessageCount = value;
    }

    /**
     * Gets the value of the deadLetterMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeadLetterMessageCount() {
        return deadLetterMessageCount;
    }

    /**
     * Sets the value of the deadLetterMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeadLetterMessageCount(Long value) {
        this.deadLetterMessageCount = value;
    }

    /**
     * Gets the value of the scheduledMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getScheduledMessageCount() {
        return scheduledMessageCount;
    }

    /**
     * Sets the value of the scheduledMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setScheduledMessageCount(Long value) {
        this.scheduledMessageCount = value;
    }

    /**
     * Gets the value of the transferMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransferMessageCount() {
        return transferMessageCount;
    }

    /**
     * Sets the value of the transferMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransferMessageCount(Long value) {
        this.transferMessageCount = value;
    }

    /**
     * Gets the value of the transferDeadLetterMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransferDeadLetterMessageCount() {
        return transferDeadLetterMessageCount;
    }

    /**
     * Sets the value of the transferDeadLetterMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransferDeadLetterMessageCount(Long value) {
        this.transferDeadLetterMessageCount = value;
    }

}
