//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NamespaceDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamespaceDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}Resource">
 *       &lt;sequence>
 *         &lt;element name="DnsLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fqdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}EntityStatus" minOccurs="0"/>
 *         &lt;element name="ServiceBusEndpoint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubscriptionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Critical" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="NamespaceType" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}NamespaceType" minOccurs="0"/>
 *         &lt;element name="MessagingSku" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *         &lt;element name="ProvisioningState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuthorizationRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AuthorizationRule" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}AuthorizationRule" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QueueDescriptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QueueDescription" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}QueueDescription" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TopicDescriptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TopicDescription" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}TopicDescription" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamespaceDescription", propOrder = {
    "dnsLabel",
    "fqdn",
    "status",
    "serviceBusEndpoint",
    "subscriptionId",
    "enabled",
    "critical",
    "namespaceType",
    "messagingSku",
    "provisioningState",
    "authorizationRules",
    "queueDescriptions",
    "topicDescriptions",
    "sku"
})
@XmlRootElement(name = "NamespaceDescription")
public class NamespaceDescription
    extends Resource
{

    @XmlElement(name = "DnsLabel")
    protected String dnsLabel;
    @XmlElement(name = "Fqdn")
    protected String fqdn;
    @XmlElement(name = "Status")
    protected EntityStatus status;
    @XmlElement(name = "ServiceBusEndpoint")
    protected String serviceBusEndpoint;
    @XmlElement(name = "SubscriptionId")
    protected String subscriptionId;
    @XmlElement(name = "Enabled")
    protected Boolean enabled;
    @XmlElement(name = "Critical")
    protected Boolean critical;
    @XmlElement(name = "NamespaceType")
    protected NamespaceType namespaceType;
    @XmlElement(name = "MessagingSku")
    protected Short messagingSku;
    @XmlElement(name = "ProvisioningState")
    protected String provisioningState;
    @XmlElement(name = "AuthorizationRules")
    protected NamespaceDescription.AuthorizationRules authorizationRules;
    @XmlElement(name = "QueueDescriptions")
    protected NamespaceDescription.QueueDescriptions queueDescriptions;
    @XmlElement(name = "TopicDescriptions")
    protected NamespaceDescription.TopicDescriptions topicDescriptions;
    
    @XmlElement(name="sku")
    protected NamespaceSku sku;
    
    public NamespaceSku getSku() {
    	return this.sku;
    }
    
    public void setSku(NamespaceSku sku) {
    	this.sku = sku;
    }

    /**
     * Gets the value of the dnsLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsLabel() {
        return dnsLabel;
    }

    /**
     * Sets the value of the dnsLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsLabel(String value) {
        this.dnsLabel = value;
    }

    /**
     * Gets the value of the fqdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFqdn() {
        return fqdn;
    }

    /**
     * Sets the value of the fqdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFqdn(String value) {
        this.fqdn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EntityStatus }
     *     
     */
    public EntityStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityStatus }
     *     
     */
    public void setStatus(EntityStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the serviceBusEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceBusEndpoint() {
        return serviceBusEndpoint;
    }

    /**
     * Sets the value of the serviceBusEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceBusEndpoint(String value) {
        this.serviceBusEndpoint = value;
    }

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionId(String value) {
        this.subscriptionId = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the critical property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCritical() {
        return critical;
    }

    /**
     * Sets the value of the critical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCritical(Boolean value) {
        this.critical = value;
    }

    /**
     * Gets the value of the namespaceType property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceType }
     *     
     */
    public NamespaceType getNamespaceType() {
        return namespaceType;
    }

    /**
     * Sets the value of the namespaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceType }
     *     
     */
    public void setNamespaceType(NamespaceType value) {
        this.namespaceType = value;
    }

    /**
     * Gets the value of the messagingSku property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMessagingSku() {
        return messagingSku;
    }

    /**
     * Sets the value of the messagingSku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMessagingSku(Short value) {
        this.messagingSku = value;
    }

    /**
     * Gets the value of the provisioningState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisioningState() {
        return provisioningState;
    }

    /**
     * Sets the value of the provisioningState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisioningState(String value) {
        this.provisioningState = value;
    }

    /**
     * Gets the value of the authorizationRules property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceDescription.AuthorizationRules }
     *     
     */
    public NamespaceDescription.AuthorizationRules getAuthorizationRules() {
        return authorizationRules;
    }

    /**
     * Sets the value of the authorizationRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceDescription.AuthorizationRules }
     *     
     */
    public void setAuthorizationRules(NamespaceDescription.AuthorizationRules value) {
        this.authorizationRules = value;
    }

    /**
     * Gets the value of the queueDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceDescription.QueueDescriptions }
     *     
     */
    public NamespaceDescription.QueueDescriptions getQueueDescriptions() {
        return queueDescriptions;
    }

    /**
     * Sets the value of the queueDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceDescription.QueueDescriptions }
     *     
     */
    public void setQueueDescriptions(NamespaceDescription.QueueDescriptions value) {
        this.queueDescriptions = value;
    }

    /**
     * Gets the value of the topicDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link NamespaceDescription.TopicDescriptions }
     *     
     */
    public NamespaceDescription.TopicDescriptions getTopicDescriptions() {
        return topicDescriptions;
    }

    /**
     * Sets the value of the topicDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamespaceDescription.TopicDescriptions }
     *     
     */
    public void setTopicDescriptions(NamespaceDescription.TopicDescriptions value) {
        this.topicDescriptions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AuthorizationRule" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}AuthorizationRule" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authorizationRules"
    })
    public static class AuthorizationRules {

        @XmlElement(name = "AuthorizationRule", required = true)
        protected List<AuthorizationRule> authorizationRules;

        /**
         * Gets the value of the authorizationRules property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the authorizationRules property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthorizationRules().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuthorizationRule }
         * 
         * 
         */
        public List<AuthorizationRule> getAuthorizationRules() {
            if (authorizationRules == null) {
                authorizationRules = new ArrayList<AuthorizationRule>();
            }
            return this.authorizationRules;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QueueDescription" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}QueueDescription" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "queueDescriptions"
    })
    public static class QueueDescriptions {

        @XmlElement(name = "QueueDescription")
        protected List<QueueDescription> queueDescriptions;

        /**
         * Gets the value of the queueDescriptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the queueDescriptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQueueDescriptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QueueDescription }
         * 
         * 
         */
        public List<QueueDescription> getQueueDescriptions() {
            if (queueDescriptions == null) {
                queueDescriptions = new ArrayList<QueueDescription>();
            }
            return this.queueDescriptions;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TopicDescription" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}TopicDescription" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "topicDescriptions"
    })
    public static class TopicDescriptions {

        @XmlElement(name = "TopicDescription")
        protected List<TopicDescription> topicDescriptions;

        /**
         * Gets the value of the topicDescriptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the topicDescriptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTopicDescriptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TopicDescription }
         * 
         * 
         */
        public List<TopicDescription> getTopicDescriptions() {
            if (topicDescriptions == null) {
                topicDescriptions = new ArrayList<TopicDescription>();
            }
            return this.topicDescriptions;
        }

    }

}
