//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.namespace.QName;
import org.joda.time.DateTime;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vcc.asb.config.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SqlRuleAction_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "SqlRuleAction");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _Filter_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "Filter");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _FalseFilter_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "FalseFilter");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _TrueFilter_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "TrueFilter");
    private final static QName _SqlFilter_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "SqlFilter");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _EmptyRuleAction_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "EmptyRuleAction");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _RuleAction_QNAME = new QName("http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", "RuleAction");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vcc.asb.config.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TopicDescription }
     * 
     */
    public TopicDescription createTopicDescription() {
        return new TopicDescription();
    }

    /**
     * Create an instance of {@link QueueDescription }
     * 
     */
    public QueueDescription createQueueDescription() {
        return new QueueDescription();
    }

    /**
     * Create an instance of {@link NamespaceDescription }
     * 
     */
    public NamespaceDescription createNamespaceDescription() {
        return new NamespaceDescription();
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link MessageCountDetails }
     * 
     */
    public MessageCountDetails createMessageCountDetails() {
        return new MessageCountDetails();
    }

    /**
     * Create an instance of {@link RuleDescription }
     * 
     */
    public RuleDescription createRuleDescription() {
        return new RuleDescription();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link RuleAction }
     * 
     */
    public RuleAction createRuleAction() {
        return new RuleAction();
    }

    /**
     * Create an instance of {@link SqlFilter }
     * 
     */
    public SqlFilter createSqlFilter() {
        return new SqlFilter();
    }

    /**
     * Create an instance of {@link SqlRuleAction }
     * 
     */
    public SqlRuleAction createSqlRuleAction() {
        return new SqlRuleAction();
    }

    /**
     * Create an instance of {@link TrueFilter }
     * 
     */
    public TrueFilter createTrueFilter() {
        return new TrueFilter();
    }

    /**
     * Create an instance of {@link TopicDescription.AuthorizationRules }
     * 
     */
    public TopicDescription.AuthorizationRules createTopicDescriptionAuthorizationRules() {
        return new TopicDescription.AuthorizationRules();
    }

    /**
     * Create an instance of {@link TopicDescription.SubscriptionDescriptions }
     * 
     */
    public TopicDescription.SubscriptionDescriptions createTopicDescriptionSubscriptionDescriptions() {
        return new TopicDescription.SubscriptionDescriptions();
    }

    /**
     * Create an instance of {@link SubscriptionDescription }
     * 
     */
    public SubscriptionDescription createSubscriptionDescription() {
        return new SubscriptionDescription();
    }

    /**
     * Create an instance of {@link QueueDescription.AuthorizationRules }
     * 
     */
    public QueueDescription.AuthorizationRules createQueueDescriptionAuthorizationRules() {
        return new QueueDescription.AuthorizationRules();
    }

    /**
     * Create an instance of {@link EmptyRuleAction }
     * 
     */
    public EmptyRuleAction createEmptyRuleAction() {
        return new EmptyRuleAction();
    }

    /**
     * Create an instance of {@link NamespaceDescription.AuthorizationRules }
     * 
     */
    public NamespaceDescription.AuthorizationRules createNamespaceDescriptionAuthorizationRules() {
        return new NamespaceDescription.AuthorizationRules();
    }

    /**
     * Create an instance of {@link NamespaceDescription.QueueDescriptions }
     * 
     */
    public NamespaceDescription.QueueDescriptions createNamespaceDescriptionQueueDescriptions() {
        return new NamespaceDescription.QueueDescriptions();
    }

    /**
     * Create an instance of {@link NamespaceDescription.TopicDescriptions }
     * 
     */
    public NamespaceDescription.TopicDescriptions createNamespaceDescriptionTopicDescriptions() {
        return new NamespaceDescription.TopicDescriptions();
    }

    /**
     * Create an instance of {@link FalseFilter }
     * 
     */
    public FalseFilter createFalseFilter() {
        return new FalseFilter();
    }

    /**
     * Create an instance of {@link Rights }
     * 
     */
    public Rights createRights() {
        return new Rights();
    }

    /**
     * Create an instance of {@link CorrelationFilter }
     * 
     */
    public CorrelationFilter createCorrelationFilter() {
        return new CorrelationFilter();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link AuthorizationRule }
     * 
     */
    public AuthorizationRule createAuthorizationRule() {
        return new AuthorizationRule();
    }

    /**
     * Create an instance of {@link Tags.Entry }
     * 
     */
    public Tags.Entry createTagsEntry() {
        return new Tags.Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SqlRuleAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "SqlRuleAction")
    public JAXBElement<SqlRuleAction> createSqlRuleAction(SqlRuleAction value) {
        return new JAXBElement<SqlRuleAction>(_SqlRuleAction_QNAME, SqlRuleAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Filter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "Filter")
    public JAXBElement<Filter> createFilter(Filter value) {
        return new JAXBElement<Filter>(_Filter_QNAME, Filter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FalseFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "FalseFilter")
    public JAXBElement<FalseFilter> createFalseFilter(FalseFilter value) {
        return new JAXBElement<FalseFilter>(_FalseFilter_QNAME, FalseFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrueFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "TrueFilter")
    public JAXBElement<TrueFilter> createTrueFilter(TrueFilter value) {
        return new JAXBElement<TrueFilter>(_TrueFilter_QNAME, TrueFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SqlFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "SqlFilter")
    public JAXBElement<SqlFilter> createSqlFilter(SqlFilter value) {
        return new JAXBElement<SqlFilter>(_SqlFilter_QNAME, SqlFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    @XmlJavaTypeAdapter(Adapter1 .class)
    public JAXBElement<DateTime> createDateTime(DateTime value) {
        return new JAXBElement<DateTime>(_DateTime_QNAME, DateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyRuleAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "EmptyRuleAction")
    public JAXBElement<EmptyRuleAction> createEmptyRuleAction(EmptyRuleAction value) {
        return new JAXBElement<EmptyRuleAction>(_EmptyRuleAction_QNAME, EmptyRuleAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect", name = "RuleAction")
    public JAXBElement<RuleAction> createRuleAction(RuleAction value) {
        return new JAXBElement<RuleAction>(_RuleAction_QNAME, RuleAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

}
