//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import org.joda.time.DateTime;


/**
 * <p>Java class for QueueDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueueDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}Resource">
 *       &lt;sequence>
 *         &lt;element name="LockDuration" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="MaxSizeInMegabytes" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RequiresDuplicateDetection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="RequiresSession" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DefaultMessageTimeToLive" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="DeadLetteringOnMessageExpiration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DuplicateDetectionHistoryTimeWindow" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="MaxDeliveryCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="EnableBatchedOperations" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SizeInBytes" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="MessageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="IsAnonymousAccessible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AuthorizationRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AuthorizationRule" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}AuthorizationRule" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Status" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}EntityStatus" minOccurs="0"/>
 *         &lt;element name="ForwardTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccessedAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="UserMetadata" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SupportOrdering" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EnablePartitioning" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EnableExpress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CountDetails" type="{http://schemas.microsoft.com/netservices/2011/06/servicebus}MessageCountDetails" minOccurs="0"/>
 *         &lt;element name="AutoDeleteOnIdle" type="{http://schemas.microsoft.com/2003/10/Serialization/}duration" minOccurs="0"/>
 *         &lt;element name="PartitioningPolicy" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}PartitioningPolicy" minOccurs="0"/>
 *         &lt;element name="EntityAvailabilityStatus" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}EntityAvailabilityStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueueDescription", propOrder = {
    "lockDuration",
    "maxSizeInMegabytes",
    "requiresDuplicateDetection",
    "requiresSession",
    "defaultMessageTimeToLive",
    "deadLetteringOnMessageExpiration",
    "duplicateDetectionHistoryTimeWindow",
    "maxDeliveryCount",
    "enableBatchedOperations",
    "sizeInBytes",
    "messageCount",
    "isAnonymousAccessible",
    "authorizationRules",
    "status",
    "forwardTo",
    "accessedAt",
    "userMetadata",
    "supportOrdering",
    "enablePartitioning",
    "enableExpress",
    "countDetails",
    "autoDeleteOnIdle",
    "partitioningPolicy",
    "entityAvailabilityStatus"
})
@XmlRootElement(name = "QueueDescription")
public class QueueDescription
    extends Resource
{

    @XmlElement(name = "LockDuration")
    protected Duration lockDuration;
    @XmlElement(name = "MaxSizeInMegabytes")
    protected Long maxSizeInMegabytes;
    @XmlElement(name = "RequiresDuplicateDetection")
    protected Boolean requiresDuplicateDetection;
    @XmlElement(name = "RequiresSession")
    protected Boolean requiresSession;
    @XmlElement(name = "DefaultMessageTimeToLive")
    protected Duration defaultMessageTimeToLive;
    @XmlElement(name = "DeadLetteringOnMessageExpiration")
    protected Boolean deadLetteringOnMessageExpiration;
    @XmlElement(name = "DuplicateDetectionHistoryTimeWindow")
    protected Duration duplicateDetectionHistoryTimeWindow;
    @XmlElement(name = "MaxDeliveryCount")
    protected Integer maxDeliveryCount;
    @XmlElement(name = "EnableBatchedOperations")
    protected Boolean enableBatchedOperations;
    @XmlElement(name = "SizeInBytes")
    protected Long sizeInBytes;
    @XmlElement(name = "MessageCount")
    protected Long messageCount;
    @XmlElement(name = "IsAnonymousAccessible")
    protected Boolean isAnonymousAccessible;
    @XmlElement(name = "AuthorizationRules")
    protected QueueDescription.AuthorizationRules authorizationRules;
    @XmlElement(name = "Status")
    protected EntityStatus status;
    @XmlElement(name = "ForwardTo")
    protected String forwardTo;
    @XmlElement(name = "AccessedAt", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime accessedAt;
    @XmlElement(name = "UserMetadata")
    protected String userMetadata;
    @XmlElement(name = "SupportOrdering")
    protected Boolean supportOrdering;
    @XmlElement(name = "EnablePartitioning")
    protected Boolean enablePartitioning;
    @XmlElement(name = "EnableExpress")
    protected Boolean enableExpress;
    @XmlElement(name = "CountDetails")
    protected MessageCountDetails countDetails;
    @XmlElement(name = "AutoDeleteOnIdle")
    protected Duration autoDeleteOnIdle;
    @XmlElement(name = "PartitioningPolicy")
    protected PartitioningPolicy partitioningPolicy;
    @XmlElement(name = "EntityAvailabilityStatus")
    protected EntityAvailabilityStatus entityAvailabilityStatus;

    /**
     * Gets the value of the lockDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getLockDuration() {
        return lockDuration;
    }

    /**
     * Sets the value of the lockDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setLockDuration(Duration value) {
        this.lockDuration = value;
    }

    /**
     * Gets the value of the maxSizeInMegabytes property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSizeInMegabytes() {
        return maxSizeInMegabytes;
    }

    /**
     * Sets the value of the maxSizeInMegabytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSizeInMegabytes(Long value) {
        this.maxSizeInMegabytes = value;
    }

    /**
     * Gets the value of the requiresDuplicateDetection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresDuplicateDetection() {
        return requiresDuplicateDetection;
    }

    /**
     * Sets the value of the requiresDuplicateDetection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresDuplicateDetection(Boolean value) {
        this.requiresDuplicateDetection = value;
    }

    /**
     * Gets the value of the requiresSession property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequiresSession() {
        return requiresSession;
    }

    /**
     * Sets the value of the requiresSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequiresSession(Boolean value) {
        this.requiresSession = value;
    }

    /**
     * Gets the value of the defaultMessageTimeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDefaultMessageTimeToLive() {
        return defaultMessageTimeToLive;
    }

    /**
     * Sets the value of the defaultMessageTimeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDefaultMessageTimeToLive(Duration value) {
        this.defaultMessageTimeToLive = value;
    }

    /**
     * Gets the value of the deadLetteringOnMessageExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeadLetteringOnMessageExpiration() {
        return deadLetteringOnMessageExpiration;
    }

    /**
     * Sets the value of the deadLetteringOnMessageExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeadLetteringOnMessageExpiration(Boolean value) {
        this.deadLetteringOnMessageExpiration = value;
    }

    /**
     * Gets the value of the duplicateDetectionHistoryTimeWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuplicateDetectionHistoryTimeWindow() {
        return duplicateDetectionHistoryTimeWindow;
    }

    /**
     * Sets the value of the duplicateDetectionHistoryTimeWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuplicateDetectionHistoryTimeWindow(Duration value) {
        this.duplicateDetectionHistoryTimeWindow = value;
    }

    /**
     * Gets the value of the maxDeliveryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDeliveryCount() {
        return maxDeliveryCount;
    }

    /**
     * Sets the value of the maxDeliveryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDeliveryCount(Integer value) {
        this.maxDeliveryCount = value;
    }

    /**
     * Gets the value of the enableBatchedOperations property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableBatchedOperations() {
        return enableBatchedOperations;
    }

    /**
     * Sets the value of the enableBatchedOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableBatchedOperations(Boolean value) {
        this.enableBatchedOperations = value;
    }

    /**
     * Gets the value of the sizeInBytes property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSizeInBytes() {
        return sizeInBytes;
    }

    /**
     * Sets the value of the sizeInBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSizeInBytes(Long value) {
        this.sizeInBytes = value;
    }

    /**
     * Gets the value of the messageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMessageCount() {
        return messageCount;
    }

    /**
     * Sets the value of the messageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMessageCount(Long value) {
        this.messageCount = value;
    }

    /**
     * Gets the value of the isAnonymousAccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAnonymousAccessible() {
        return isAnonymousAccessible;
    }

    /**
     * Sets the value of the isAnonymousAccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAnonymousAccessible(Boolean value) {
        this.isAnonymousAccessible = value;
    }

    /**
     * Gets the value of the authorizationRules property.
     * 
     * @return
     *     possible object is
     *     {@link QueueDescription.AuthorizationRules }
     *     
     */
    public QueueDescription.AuthorizationRules getAuthorizationRules() {
        return authorizationRules;
    }

    /**
     * Sets the value of the authorizationRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueDescription.AuthorizationRules }
     *     
     */
    public void setAuthorizationRules(QueueDescription.AuthorizationRules value) {
        this.authorizationRules = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link EntityStatus }
     *     
     */
    public EntityStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityStatus }
     *     
     */
    public void setStatus(EntityStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the forwardTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwardTo() {
        return forwardTo;
    }

    /**
     * Sets the value of the forwardTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwardTo(String value) {
        this.forwardTo = value;
    }

    /**
     * Gets the value of the accessedAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getAccessedAt() {
        return accessedAt;
    }

    /**
     * Sets the value of the accessedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessedAt(DateTime value) {
        this.accessedAt = value;
    }

    /**
     * Gets the value of the userMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserMetadata() {
        return userMetadata;
    }

    /**
     * Sets the value of the userMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserMetadata(String value) {
        this.userMetadata = value;
    }

    /**
     * Gets the value of the supportOrdering property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSupportOrdering() {
        return supportOrdering;
    }

    /**
     * Sets the value of the supportOrdering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportOrdering(Boolean value) {
        this.supportOrdering = value;
    }

    /**
     * Gets the value of the enablePartitioning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnablePartitioning() {
        return enablePartitioning;
    }

    /**
     * Sets the value of the enablePartitioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnablePartitioning(Boolean value) {
        this.enablePartitioning = value;
    }

    /**
     * Gets the value of the enableExpress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableExpress() {
        return enableExpress;
    }

    /**
     * Sets the value of the enableExpress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableExpress(Boolean value) {
        this.enableExpress = value;
    }

    /**
     * Gets the value of the countDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MessageCountDetails }
     *     
     */
    public MessageCountDetails getCountDetails() {
        return countDetails;
    }

    /**
     * Sets the value of the countDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageCountDetails }
     *     
     */
    public void setCountDetails(MessageCountDetails value) {
        this.countDetails = value;
    }

    /**
     * Gets the value of the autoDeleteOnIdle property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAutoDeleteOnIdle() {
        return autoDeleteOnIdle;
    }

    /**
     * Sets the value of the autoDeleteOnIdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAutoDeleteOnIdle(Duration value) {
        this.autoDeleteOnIdle = value;
    }

    /**
     * Gets the value of the partitioningPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link PartitioningPolicy }
     *     
     */
    public PartitioningPolicy getPartitioningPolicy() {
        return partitioningPolicy;
    }

    /**
     * Sets the value of the partitioningPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartitioningPolicy }
     *     
     */
    public void setPartitioningPolicy(PartitioningPolicy value) {
        this.partitioningPolicy = value;
    }

    /**
     * Gets the value of the entityAvailabilityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EntityAvailabilityStatus }
     *     
     */
    public EntityAvailabilityStatus getEntityAvailabilityStatus() {
        return entityAvailabilityStatus;
    }

    /**
     * Sets the value of the entityAvailabilityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityAvailabilityStatus }
     *     
     */
    public void setEntityAvailabilityStatus(EntityAvailabilityStatus value) {
        this.entityAvailabilityStatus = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AuthorizationRule" type="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}AuthorizationRule" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authorizationRules"
    })
    public static class AuthorizationRules {

        @XmlElement(name = "AuthorizationRule", required = true)
        protected List<AuthorizationRule> authorizationRules;

        /**
         * Gets the value of the authorizationRules property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the authorizationRules property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuthorizationRules().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuthorizationRule }
         * 
         * 
         */
        public List<AuthorizationRule> getAuthorizationRules() {
            if (authorizationRules == null) {
                authorizationRules = new ArrayList<AuthorizationRule>();
            }
            return this.authorizationRules;
        }

    }

}
