//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.20 at 06:25:51 PM CET 
//


package com.vcc.asb.config.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SqlFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SqlFilter">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/netservices/2010/10/servicebus/connect}Filter">
 *       &lt;sequence>
 *         &lt;element name="SqlExpression" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompatibilityLevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SqlFilter", propOrder = {
    "sqlExpression",
    "compatibilityLevel"
})
@XmlSeeAlso({
    TrueFilter.class,
    FalseFilter.class
})
public class SqlFilter
    extends Filter
{

    @XmlElement(name = "SqlExpression")
    protected String sqlExpression;
    @XmlElement(name = "CompatibilityLevel")
    protected Integer compatibilityLevel;

    /**
     * Gets the value of the sqlExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqlExpression() {
        return sqlExpression;
    }

    /**
     * Sets the value of the sqlExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqlExpression(String value) {
        this.sqlExpression = value;
    }

    /**
     * Gets the value of the compatibilityLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCompatibilityLevel() {
        return compatibilityLevel;
    }

    /**
     * Sets the value of the compatibilityLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCompatibilityLevel(Integer value) {
        this.compatibilityLevel = value;
    }

}
