//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Base complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Base">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NamespaceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResourceGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MonitorMetricsTimeGrain" type="{http://schemas.microsoft.com/windowsazure}MonitorMetricsTimeGrain" minOccurs="0"/>
 *         &lt;element name="RollupMetricsTimeGrain" type="{http://schemas.microsoft.com/windowsazure}TimeGrain" minOccurs="0"/>
 *         &lt;element name="TimeInterval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Timespan" type="{http://schemas.microsoft.com/windowsazure}Timespan" minOccurs="0"/>
 *         &lt;element name="FailureMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Base", propOrder = {
    "namespaceName",
    "resourceGroupName",
    "monitorMetricsTimeGrain",
    "rollupMetricsTimeGrain",
    "timeInterval",
    "timespan",
    "failureMessage"
})
@XmlSeeAlso({
    NamespaceMetrics.class,
    BaseMetrics.class
})
public class Base {

    @XmlElement(name = "NamespaceName")
    protected String namespaceName;
    @XmlElement(name = "ResourceGroupName")
    protected String resourceGroupName;
    @XmlElement(name = "MonitorMetricsTimeGrain")
    protected MonitorMetricsTimeGrain monitorMetricsTimeGrain;
    @XmlElement(name = "RollupMetricsTimeGrain")
    protected TimeGrain rollupMetricsTimeGrain;
    @XmlElement(name = "TimeInterval")
    protected String timeInterval;
    @XmlElement(name = "Timespan")
    protected Timespan timespan;
    @XmlElement(name = "FailureMessage")
    protected String failureMessage;

    /**
     * Gets the value of the namespaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespaceName() {
        return namespaceName;
    }

    /**
     * Sets the value of the namespaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespaceName(String value) {
        this.namespaceName = value;
    }

    /**
     * Gets the value of the resourceGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceGroupName() {
        return resourceGroupName;
    }

    /**
     * Sets the value of the resourceGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceGroupName(String value) {
        this.resourceGroupName = value;
    }

    /**
     * Gets the value of the monitorMetricsTimeGrain property.
     * 
     * @return
     *     possible object is
     *     {@link MonitorMetricsTimeGrain }
     *     
     */
    public MonitorMetricsTimeGrain getMonitorMetricsTimeGrain() {
        return monitorMetricsTimeGrain;
    }

    /**
     * Sets the value of the monitorMetricsTimeGrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitorMetricsTimeGrain }
     *     
     */
    public void setMonitorMetricsTimeGrain(MonitorMetricsTimeGrain value) {
        this.monitorMetricsTimeGrain = value;
    }

    /**
     * Gets the value of the rollupMetricsTimeGrain property.
     * 
     * @return
     *     possible object is
     *     {@link TimeGrain }
     *     
     */
    public TimeGrain getRollupMetricsTimeGrain() {
        return rollupMetricsTimeGrain;
    }

    /**
     * Sets the value of the rollupMetricsTimeGrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeGrain }
     *     
     */
    public void setRollupMetricsTimeGrain(TimeGrain value) {
        this.rollupMetricsTimeGrain = value;
    }

    /**
     * Gets the value of the timeInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeInterval() {
        return timeInterval;
    }

    /**
     * Sets the value of the timeInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeInterval(String value) {
        this.timeInterval = value;
    }

    /**
     * Gets the value of the timespan property.
     * 
     * @return
     *     possible object is
     *     {@link Timespan }
     *     
     */
    public Timespan getTimespan() {
        return timespan;
    }

    /**
     * Sets the value of the timespan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timespan }
     *     
     */
    public void setTimespan(Timespan value) {
        this.timespan = value;
    }

    /**
     * Gets the value of the failureMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailureMessage() {
        return failureMessage;
    }

    /**
     * Sets the value of the failureMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailureMessage(String value) {
        this.failureMessage = value;
    }

}
