//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseMetrics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseMetrics">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/windowsazure}Base">
 *       &lt;sequence>
 *         &lt;element name="requests_total" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requests_successful" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requests_failed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requests_failed_internalservererror" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requests_failed_serverbusy" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="requests_failed_other" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ActiveMessageCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DeadLetterMessageCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ScheduledMessageCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TransferMessageCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TransferDeadLetterMessageCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseMetrics", propOrder = {
    "requestsTotal",
    "requestsSuccessful",
    "requestsFailed",
    "requestsFailedInternalservererror",
    "requestsFailedServerbusy",
    "requestsFailedOther",
    "activeMessageCount",
    "deadLetterMessageCount",
    "scheduledMessageCount",
    "transferMessageCount",
    "transferDeadLetterMessageCount"
})
@XmlSeeAlso({
    SubscriptionMetrics.class,
    TopicMetrics.class,
    QueueMetrics.class
})
public class BaseMetrics
    extends Base
{

    @XmlElement(name = "requests_total")
    protected Integer requestsTotal;
    @XmlElement(name = "requests_successful")
    protected Integer requestsSuccessful;
    @XmlElement(name = "requests_failed")
    protected Integer requestsFailed;
    @XmlElement(name = "requests_failed_internalservererror")
    protected Integer requestsFailedInternalservererror;
    @XmlElement(name = "requests_failed_serverbusy")
    protected Integer requestsFailedServerbusy;
    @XmlElement(name = "requests_failed_other")
    protected Integer requestsFailedOther;
    @XmlElement(name = "ActiveMessageCount")
    protected Integer activeMessageCount;
    @XmlElement(name = "DeadLetterMessageCount")
    protected Integer deadLetterMessageCount;
    @XmlElement(name = "ScheduledMessageCount")
    protected Integer scheduledMessageCount;
    @XmlElement(name = "TransferMessageCount")
    protected Integer transferMessageCount;
    @XmlElement(name = "TransferDeadLetterMessageCount")
    protected Integer transferDeadLetterMessageCount;

    /**
     * Gets the value of the requestsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsTotal() {
        return requestsTotal;
    }

    /**
     * Sets the value of the requestsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsTotal(Integer value) {
        this.requestsTotal = value;
    }

    /**
     * Gets the value of the requestsSuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsSuccessful() {
        return requestsSuccessful;
    }

    /**
     * Sets the value of the requestsSuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsSuccessful(Integer value) {
        this.requestsSuccessful = value;
    }

    /**
     * Gets the value of the requestsFailed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsFailed() {
        return requestsFailed;
    }

    /**
     * Sets the value of the requestsFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsFailed(Integer value) {
        this.requestsFailed = value;
    }

    /**
     * Gets the value of the requestsFailedInternalservererror property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsFailedInternalservererror() {
        return requestsFailedInternalservererror;
    }

    /**
     * Sets the value of the requestsFailedInternalservererror property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsFailedInternalservererror(Integer value) {
        this.requestsFailedInternalservererror = value;
    }

    /**
     * Gets the value of the requestsFailedServerbusy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsFailedServerbusy() {
        return requestsFailedServerbusy;
    }

    /**
     * Sets the value of the requestsFailedServerbusy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsFailedServerbusy(Integer value) {
        this.requestsFailedServerbusy = value;
    }

    /**
     * Gets the value of the requestsFailedOther property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestsFailedOther() {
        return requestsFailedOther;
    }

    /**
     * Sets the value of the requestsFailedOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestsFailedOther(Integer value) {
        this.requestsFailedOther = value;
    }

    /**
     * Gets the value of the activeMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActiveMessageCount() {
        return activeMessageCount;
    }

    /**
     * Sets the value of the activeMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActiveMessageCount(Integer value) {
        this.activeMessageCount = value;
    }

    /**
     * Gets the value of the deadLetterMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeadLetterMessageCount() {
        return deadLetterMessageCount;
    }

    /**
     * Sets the value of the deadLetterMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeadLetterMessageCount(Integer value) {
        this.deadLetterMessageCount = value;
    }

    /**
     * Gets the value of the scheduledMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getScheduledMessageCount() {
        return scheduledMessageCount;
    }

    /**
     * Sets the value of the scheduledMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScheduledMessageCount(Integer value) {
        this.scheduledMessageCount = value;
    }

    /**
     * Gets the value of the transferMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransferMessageCount() {
        return transferMessageCount;
    }

    /**
     * Sets the value of the transferMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransferMessageCount(Integer value) {
        this.transferMessageCount = value;
    }

    /**
     * Gets the value of the transferDeadLetterMessageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransferDeadLetterMessageCount() {
        return transferDeadLetterMessageCount;
    }

    /**
     * Sets the value of the transferDeadLetterMessageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransferDeadLetterMessageCount(Integer value) {
        this.transferDeadLetterMessageCount = value;
    }

}
