//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitorMetricsTimeGrain.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MonitorMetricsTimeGrain">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PT1M"/>
 *     &lt;enumeration value="PT1H"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MonitorMetricsTimeGrain")
@XmlEnum
public enum MonitorMetricsTimeGrain {

    @XmlEnumValue("PT1M")
    PT_1_M("PT1M"),
    @XmlEnumValue("PT1H")
    PT_1_H("PT1H");
    private final String value;

    MonitorMetricsTimeGrain(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MonitorMetricsTimeGrain fromValue(String v) {
        for (MonitorMetricsTimeGrain c: MonitorMetricsTimeGrain.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
