//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NamespaceMetrics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamespaceMetrics">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/windowsazure}Base">
 *       &lt;sequence>
 *         &lt;element name="SuccessfulRequests" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ServerErrors" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="UserErrors" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThrottledRequests" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IncomingRequests" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IncomingMessages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="OutgoingMessages" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ActiveConnections" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ConnectionsOpened" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ConnectionsClosed" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamespaceMetrics", propOrder = {
    "successfulRequests",
    "serverErrors",
    "userErrors",
    "throttledRequests",
    "incomingRequests",
    "incomingMessages",
    "outgoingMessages",
    "activeConnections",
    "connectionsOpened",
    "connectionsClosed"
})
@XmlRootElement(name = "NamespaceMetrics")
public class NamespaceMetrics
    extends Base
{

    @XmlElement(name = "SuccessfulRequests")
    protected Integer successfulRequests;
    @XmlElement(name = "ServerErrors")
    protected Integer serverErrors;
    @XmlElement(name = "UserErrors")
    protected Integer userErrors;
    @XmlElement(name = "ThrottledRequests")
    protected Integer throttledRequests;
    @XmlElement(name = "IncomingRequests")
    protected Integer incomingRequests;
    @XmlElement(name = "IncomingMessages")
    protected Integer incomingMessages;
    @XmlElement(name = "OutgoingMessages")
    protected Integer outgoingMessages;
    @XmlElement(name = "ActiveConnections")
    protected Integer activeConnections;
    @XmlElement(name = "ConnectionsOpened")
    protected Integer connectionsOpened;
    @XmlElement(name = "ConnectionsClosed")
    protected Integer connectionsClosed;

    /**
     * Gets the value of the successfulRequests property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSuccessfulRequests() {
        return successfulRequests;
    }

    /**
     * Sets the value of the successfulRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSuccessfulRequests(Integer value) {
        this.successfulRequests = value;
    }

    /**
     * Gets the value of the serverErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServerErrors() {
        return serverErrors;
    }

    /**
     * Sets the value of the serverErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServerErrors(Integer value) {
        this.serverErrors = value;
    }

    /**
     * Gets the value of the userErrors property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUserErrors() {
        return userErrors;
    }

    /**
     * Sets the value of the userErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUserErrors(Integer value) {
        this.userErrors = value;
    }

    /**
     * Gets the value of the throttledRequests property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThrottledRequests() {
        return throttledRequests;
    }

    /**
     * Sets the value of the throttledRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThrottledRequests(Integer value) {
        this.throttledRequests = value;
    }

    /**
     * Gets the value of the incomingRequests property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIncomingRequests() {
        return incomingRequests;
    }

    /**
     * Sets the value of the incomingRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIncomingRequests(Integer value) {
        this.incomingRequests = value;
    }

    /**
     * Gets the value of the incomingMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIncomingMessages() {
        return incomingMessages;
    }

    /**
     * Sets the value of the incomingMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIncomingMessages(Integer value) {
        this.incomingMessages = value;
    }

    /**
     * Gets the value of the outgoingMessages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOutgoingMessages() {
        return outgoingMessages;
    }

    /**
     * Sets the value of the outgoingMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOutgoingMessages(Integer value) {
        this.outgoingMessages = value;
    }

    /**
     * Gets the value of the activeConnections property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActiveConnections() {
        return activeConnections;
    }

    /**
     * Sets the value of the activeConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActiveConnections(Integer value) {
        this.activeConnections = value;
    }

    /**
     * Gets the value of the connectionsOpened property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConnectionsOpened() {
        return connectionsOpened;
    }

    /**
     * Sets the value of the connectionsOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConnectionsOpened(Integer value) {
        this.connectionsOpened = value;
    }

    /**
     * Gets the value of the connectionsClosed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConnectionsClosed() {
        return connectionsClosed;
    }

    /**
     * Sets the value of the connectionsClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConnectionsClosed(Integer value) {
        this.connectionsClosed = value;
    }

}
