//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vcc.asb.metrics.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vcc.asb.metrics.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetricValueSetCollection }
     * 
     */
    public MetricValueSetCollection createMetricValueSetCollection() {
        return new MetricValueSetCollection();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link QueueMetrics }
     * 
     */
    public QueueMetrics createQueueMetrics() {
        return new QueueMetrics();
    }

    /**
     * Create an instance of {@link BaseMetrics }
     * 
     */
    public BaseMetrics createBaseMetrics() {
        return new BaseMetrics();
    }

    /**
     * Create an instance of {@link Base }
     * 
     */
    public Base createBase() {
        return new Base();
    }

    /**
     * Create an instance of {@link Timespan }
     * 
     */
    public Timespan createTimespan() {
        return new Timespan();
    }

    /**
     * Create an instance of {@link TopicMetrics }
     * 
     */
    public TopicMetrics createTopicMetrics() {
        return new TopicMetrics();
    }

    /**
     * Create an instance of {@link NamespaceMetrics }
     * 
     */
    public NamespaceMetrics createNamespaceMetrics() {
        return new NamespaceMetrics();
    }

    /**
     * Create an instance of {@link SubscriptionMetrics }
     * 
     */
    public SubscriptionMetrics createSubscriptionMetrics() {
        return new SubscriptionMetrics();
    }

    /**
     * Create an instance of {@link MetricValueSet }
     * 
     */
    public MetricValueSet createMetricValueSet() {
        return new MetricValueSet();
    }

    /**
     * Create an instance of {@link MetricValues }
     * 
     */
    public MetricValues createMetricValues() {
        return new MetricValues();
    }

    /**
     * Create an instance of {@link MetricValue }
     * 
     */
    public MetricValue createMetricValue() {
        return new MetricValue();
    }

}
