//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 11:17:35 AM CET 
//


package com.vcc.asb.metrics.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeGrain.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimeGrain">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PT5M"/>
 *     &lt;enumeration value="PT1H"/>
 *     &lt;enumeration value="P1D"/>
 *     &lt;enumeration value="P7D"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimeGrain")
@XmlEnum
public enum TimeGrain {

    @XmlEnumValue("PT5M")
    PT_5_M("PT5M"),
    @XmlEnumValue("PT1H")
    PT_1_H("PT1H"),
    @XmlEnumValue("P1D")
    P_1_D("P1D"),
    @XmlEnumValue("P7D")
    P_7_D("P7D");
    private final String value;

    TimeGrain(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeGrain fromValue(String v) {
        for (TimeGrain c: TimeGrain.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
